version: '3.8'

services:
  # Development server for OHIF Viewer
  ohif_dev:
    build:
      # 프로젝트 루트 디렉토리로 컨텍스트 설정
      context: ../../../../
      dockerfile: platform/app/.recipes/Nginx-Orthanc-custom/dockerfile.dev
    image: ohif-dev:latest
    container_name: ohif_dev
    volumes:
      # 소스 코드 마운트 (루트 디렉토리)
      - ../../../../:/app
      # node_modules 제외
      - /app/node_modules
    ports:
      - '3000:3000' # Dev server port
    environment:
      - NODE_ENV=development
      - APP_CONFIG=config/default.js
    command: yarn run dev
    restart: unless-stopped

  # Orthanc DICOM server
  orthanc:
    image: jodogne/orthanc-plugins
    hostname: orthanc
    container_name: orthanc_dev
    volumes:
      # Config
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    restart: unless-stopped
    ports:
      - '4242:4242' # Orthanc REST API
      - '8042:8042' # Orthanc HTTP

networks:
  default:
    name: ohif-dev-network
